### ISSUE TITLE
登录代码

### ISSUE THREAD

**Issue by donne1226** [SouthernBox/IceAndFire-WeiXin#1]
在掘金上看到你发的文章https://juejin.im/post/594ddaa8f265da6c4e7f3d8b。
关于登录这一块的代码你提交一下吧。 
借鉴一下。-感谢

**Comment by NanBox** [comment]
你好，之前写的这个获取用户信息的方法，现在已经不建议使用了。
可以参考：http://developers.weixin.qq.com/blogdetail?action=get_post_info&lang=zh_CN&token=&docid=c45683ebfa39ce8fe71def0631fad26b

**Comment by donne1226** [comment]
@SouthernBox 感谢！
